@startuml
'https://plantuml.com/class-diagram

class Lampe
class Hifi
class Appareil
class Telecommande

Appareil "*" <-- Telecommande : -appareils
Appareil <|-- Lampe
Appareil <|-- Hifi
Appareil <|-- Television

@enduml